# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package-name: [ "brotli-internal", "brotli"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      
    - name: 'Set up OpenJDK 17'
      if: ${{matrix.package-name == 'brotli'}}
      uses: actions/setup-java@v3
      with:
        distribution: 17
        java-version: "temurin"

    - name: 'Set up OracleJDK 17'
      if: ${{matrix.package-name == 'brotli-internal'}}
      uses: oracle-actions/setup-java@a87a2fe2455ed045ab1559f0be38be5092e74f4f
      with:
       release: 17
       website: oracle.com

    - name: Publish to GitHub Packages
      working-directory: ${{ github.workspace }}/java/org/brotli
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PACKAGE_NAME: ${{ matrix.package-name }}