# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package-name: [ "brotli-internal", "brotli"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up JDK 17 for toolchains
      uses: oracle-actions/setup-java@eb2ce81d5de20acbc5dd7044b9ecd874ce5ec2d6
      with:
        uri: https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz

    - name: 'Set up OracleJDK 17'
      if: ${{matrix.package-name == 'brotli-internal'}}
      uses: oracle-actions/setup-java@a87a2fe2455ed045ab1559f0be38be5092e74f4f
      with:
       release: 17
       website: oracle.com

    - name: Publish to GitHub Packages
      working-directory: ${{ github.workspace }}/java/org/brotli
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PACKAGE_NAME: ${{ matrix.package-name }}
