name: Release
on:
  release:
    types:
      - created
permissions:
  contents: write
jobs:
  build:
    name: Upload Release Assets
    strategy:
      matrix:
        name: [ linux_x64, macos_x64, macos_arm64 ]
        include:
          - os: ubuntu-latest
            name: linux_x64
            cpu: k8
          - os: macOS-latest
            name: macos_x64
            cpu: darwin_x86_64
          - os: macOS-latest
            name: macos_arm64
            cpu: darwin_arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          bazel build -c opt --cpu=${{ matrix.cpu }} //org/brotli/wrapper:wrapper_deploy.jar
          bazel build -c opt --cpu=${{ matrix.cpu }} //org/brotli/wrapper:native
          mv ./bazel-bin/org/brotli/wrapper/wrapper_deploy.jar ../brotli.jar
          mv ./bazel-bin/org/brotli/wrapper/native.jar ../brotli-native-${{ matrix.name }}.jar
        working-directory: ./java
      - name: Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            brotli.jar
            brotli-native-${{ matrix.name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
